
#General Settings
[general]
	#Base rpm creatures can spin the horse crank.
	#Range: > 1
	creatureRPMRange = 16
	#How much stress small creatures can produce for the horse crank.
	#Range: > 1
	smallCreatureStressRange = 128
	#How much stress medium creatures can produce for the horse crank.
	#Range: > 1
	mediumCreatureStressRange = 256
	#How much stress large creatures can produce for the horse crank.
	#Range: > 1
	largeCreatureStressRange = 512

#Path Category
[paths]
	#Types of blocks valid as "Poor" quality,
	poor_path_block = ["tfc:dirt/silt", "tfc:dirt/loam", "tfc:dirt/sandy_loam", "tfc:dirt/silty_loam"]
	#Types of blocks valid as "Normal" quality,
	normal_path_block = ["tfc:grass_path/silt", "tfc:grass_path/loam", "tfc:grass_path/sandy_loam", "tfc:grass_path/silty_loam"]
	#Types of blocks valid as "Great" quality,
	great_path_block = ["iceandfire:frozen_dirt_path", "createdieselgenerators:asphalt_block", "iceandfire:dragon_ice"]

#Creature Category
[workers]
	#Valid "Small" creatures
	small_creatures = ["tfc:wolf", "tfc:boar", "tfc:goat"]
	#Valid "Medium" creatures
	medium_creatures = [ "tfc:alpaca", "tfc:sheep", "tfc:yak", "minecraft:villager"]
	#Valid "Large" creatures
	large_creatures = ["tfc:horse", "tfc:mule", "tfc:donkey", "tfc:cow"]

